import { useEffect, useState } from 'react';
import { Building2, ListMusic, Plus, Search, Trash2, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useCoramApp } from '../../../app/CoramAppContext';
import { EditorialHeading, ExperienceCanvas, StatePanel } from '../../../components/experience-v2/ExperienceV2';
import { organizationsRepository, type Organization } from '../../../domain/organizations/organizationsRepository';
import { repertoireRepository, type RepertoireSong } from '../../../domain/repertoire/repertoireRepository';
import { servicesRepository, type MinistryService } from '../../../domain/services/servicesRepository';
import styles from './Repertoire.module.css';

export function RepertoirePage() {
  const { auth } = useCoramApp(); const [scope,setScope]=useState<'personal'|'organization'>('personal'); const [organizations,setOrganizations]=useState<Organization[]>([]); const [organizationId,setOrganizationId]=useState(''); const [songs,setSongs]=useState<RepertoireSong[]>([]); const [services,setServices]=useState<MinistryService[]>([]); const [search,setSearch]=useState(''); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{organizationsRepository.list().then((items)=>{setOrganizations(items);setOrganizationId(items[0]?.id??'');}).catch(()=>undefined);},[]);
  const load=async()=>{try{const next=scope==='personal'&&auth.profile?.id?await repertoireRepository.listPersonalSongs(auth.profile.id,search):organizationId?await repertoireRepository.listOrganizationSongs(organizationId,search):[];setSongs(next);if(scope==='organization'&&organizationId)setServices(await servicesRepository.listUpcoming(organizationId));else setServices([]);}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible cargar el repertorio.');}};
  useEffect(()=>{void load();},[scope,organizationId,auth.profile?.id]);
  async function remove(song:RepertoireSong){if(!confirm(`¿Eliminar "${song.title}"?`))return;try{if(scope==='personal'&&auth.profile?.id)await repertoireRepository.deletePersonalSong(song.id,auth.profile.id);else if(organizationId)await repertoireRepository.deleteOrganizationSong(song.id,organizationId);await load();}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible eliminar.');}}
  async function addToNextService(song:RepertoireSong){const service=services[0];if(!service)return;try{await repertoireRepository.addSongToService(service.id,organizationId,song.id); }catch(reason){setError(reason instanceof Error?reason.message:'No fue posible asociar la canción.');}}
  const editorScope=scope==='personal'?`scope=personal`:`scope=organization&organization=${organizationId}`;
  return <ExperienceCanvas><EditorialHeading eyebrow="Biblioteca propia" title="Repertorio" body="Tu repertorio personal permanece privado. El repertorio de Ministerio se comparte solo con miembros autorizados." icon={ListMusic}/><div className={styles.toolbar}><div className={styles.tabs}><button data-active={scope==='personal'} onClick={()=>setScope('personal')}><UserRound/>Personal</button><button data-active={scope==='organization'} onClick={()=>setScope('organization')} disabled={!organizations.length}><Building2/>Ministerio</button></div>{scope==='organization'&&<select value={organizationId} onChange={(event)=>setOrganizationId(event.target.value)}>{organizations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}<form onSubmit={(event)=>{event.preventDefault();void load();}} className={styles.search}><Search/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Buscar canción"/><button>Buscar</button></form><Link to={`/app/repertorio/nueva?${editorScope}`}><Plus/>Nueva canción</Link></div>{error&&<p className={styles.error}>{error}</p>}{songs.length===0?<StatePanel icon={ListMusic} title="Tu repertorio está listo para comenzar" body={scope==='personal'?'Las canciones que crees aquí serán privadas.':'Las canciones del ministerio aparecerán para sus miembros.'}/>:<div className={styles.songGrid}>{songs.map((song)=><article key={song.id} className={styles.songCard}><div><small>{song.musicalKey||'Sin tono'}{song.bpm?` · ${song.bpm} BPM`:''}</small><h2>{song.title}</h2><p>{song.artist||'Autor no indicado'}</p></div><div className={styles.cardActions}><Link to={`/app/repertorio/${song.id}?${editorScope}`}>Editar</Link>{scope==='organization'&&services[0]&&<button onClick={()=>void addToNextService(song)}>Añadir a {services[0].title}</button>}<button aria-label="Eliminar" onClick={()=>void remove(song)}><Trash2/></button></div></article>)}</div>}</ExperienceCanvas>;
}
