import { type FormEvent, useEffect, useState } from 'react';
import { Music2 } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { transposeChordText } from '@coram/shared-domain';
import { useCoramApp } from '../../../app/CoramAppContext';
import { EditorialCard, EditorialHeading, ExperienceCanvas } from '../../../components/experience-v2/ExperienceV2';
import { repertoireRepository, type SongInput } from '../../../domain/repertoire/repertoireRepository';
import styles from './Repertoire.module.css';

export function SongEditorPage(){const {songId}=useParams();const [params]=useSearchParams();const navigate=useNavigate();const {auth}=useCoramApp();const scope=params.get('scope')==='organization'?'organization':'personal';const organizationId=params.get('organization')??'';const [values,setValues]=useState<SongInput>({title:''});const [shift,setShift]=useState(0);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!songId||songId==='nueva')return;const request=scope==='personal'&&auth.profile?.id?repertoireRepository.getPersonalSong(songId,auth.profile.id):organizationId?repertoireRepository.getOrganizationSong(songId,organizationId):null;request?.then((song)=>setValues({title:song.title,artist:song.artist??'',musicalKey:song.musicalKey??'',bpm:song.bpm,lyrics:song.lyrics??'',chords:song.chords??'',notes:song.notes??''})).catch((reason)=>setError(reason.message));},[songId,scope,organizationId,auth.profile?.id]);
  const set=(name:keyof SongInput,value:string|number|null)=>setValues((current)=>({...current,[name]:value}));
  async function save(event:FormEvent){event.preventDefault();try{if(songId&&songId!=='nueva'){if(scope==='personal'&&auth.profile?.id)await repertoireRepository.updatePersonalSong(songId,auth.profile.id,values);else await repertoireRepository.updateOrganizationSong(songId,organizationId,values);}else if(scope==='personal')await repertoireRepository.createPersonalSong(values);else await repertoireRepository.createOrganizationSong(organizationId,values);navigate('/app/repertorio');}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible guardar.');}}
  return <ExperienceCanvas><Link className={styles.back} to="/app/repertorio">Volver al repertorio</Link><EditorialHeading eyebrow={scope==='personal'?'Repertorio privado':'Repertorio del ministerio'} title={songId&&songId!=='nueva'?'Editar canción':'Nueva canción'} body="Guarda tono, tempo, letra y acordes sin mezclar los ámbitos personal y compartido." icon={Music2}/><EditorialCard className={styles.editorCard}>{error&&<p className={styles.error}>{error}</p>}<form onSubmit={save} className={styles.editor}><label>Título<input value={values.title} onChange={(e)=>set('title',e.target.value)} required/></label><label>Autor<input value={values.artist??''} onChange={(e)=>set('artist',e.target.value)}/></label><label>Tono<input value={values.musicalKey??''} onChange={(e)=>set('musicalKey',e.target.value)} placeholder="C"/></label><label>BPM<input type="number" min="20" max="320" value={values.bpm??''} onChange={(e)=>set('bpm',e.target.value?Number(e.target.value):null)}/></label><label className={styles.wide}>Letra<textarea value={values.lyrics??''} onChange={(e)=>set('lyrics',e.target.value)} rows={8}/></label><label className={styles.wide}>Acordes<textarea value={values.chords??''} onChange={(e)=>set('chords',e.target.value)} rows={6}/></label><label className={styles.wide}>Notas<textarea value={values.notes??''} onChange={(e)=>set('notes',e.target.value)} rows={3}/></label><button type="submit">Guardar canción</button></form>{values.chords&&<section className={styles.preview}><div><strong>Vista transpuesta</strong><select value={shift} onChange={(e)=>setShift(Number(e.target.value))}>{Array.from({length:12},(_,index)=>index-5).map((value)=><option key={value} value={value}>{value>0?`+${value}`:value} semitonos</option>)}</select></div><pre>{transposeChordText(values.chords,shift)}</pre></section>}</EditorialCard></ExperienceCanvas>}
